/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package WSwingUILib.Component;

import WSwingUILib.Component.Base.JImagePanel;
import javax.swing.ImageIcon;

/**
 *
 * @author xyuser
 */
public class JTabButton extends JImagePanel {

    private ImageIcon pressImage;
    private ImageIcon releaseImage;
    private Boolean isPressed = false;
    public JMiddleContentPanel content = null;
    public Object tag = null;

    /**
     * Creates new form JTabButton
     */
    public JTabButton() {
        initComponents();
        pressImage = JImagePanel.getImageIconObjFromResource("/WSwingUILib/UIImage/tabselected.png");
        releaseImage = JImagePanel.getImageIconObjFromResource("/WSwingUILib/UIImage/releasetab.png");
        processReleaseButton();
    }

    /**
     * 设置标签图标
     * @param image 
     */
    public void setTabImage(ImageIcon image)
    {
        this.plImage.setImageIcon(image, false);
        this.nowPaint();
    }
    
    /**
     * 设置标签按钮文本
     * @param name 
     */
    public void setTabText(String name)
    {
        this.lblName.setText(name);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plImage = new WSwingUILib.Component.Base.JImagePanel();
        lblName = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        javax.swing.GroupLayout plImageLayout = new javax.swing.GroupLayout(plImage);
        plImage.setLayout(plImageLayout);
        plImageLayout.setHorizontalGroup(
            plImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );
        plImageLayout.setVerticalGroup(
            plImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        lblName.setFont(new java.awt.Font("文泉驿微米黑", 1, 12)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("jLabel1");
        lblName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNameMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(plImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(plImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * 按下
     */
    public void processPressButton() {
        if (!isPressed) {
            this.setImageIcon(pressImage, false);
            this.nowPaint();
            isPressed = true;
        }
    }

    /**
     * 抬起
     */
    public void processReleaseButton() {
        this.setImageIcon(releaseImage, false);
        this.nowPaint();
        isPressed = false;
    }

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        processPressButton();
    }//GEN-LAST:event_formMouseClicked

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
        this.setImageIcon(pressImage, false);
        this.nowPaint();
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        // TODO add your handling code here:
        if (!this.isPressed)
        {
            this.setImageIcon(releaseImage, false);
            this.nowPaint();
        }
    }//GEN-LAST:event_formMouseExited

    private void lblNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNameMouseClicked
        // TODO add your handling code here:
        this.processMouseEvent(evt);
    }//GEN-LAST:event_lblNameMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblName;
    private WSwingUILib.Component.Base.JImagePanel plImage;
    // End of variables declaration//GEN-END:variables
}
